#ifndef STRINGMANIPULATION_GLOBAL_H
#define STRINGMANIPULATION_GLOBAL_H

#if defined(STRINGMANIPULATION_LIBRARY)
#  define STRINGMANIPULATION_EXPORT Q_DECL_EXPORT
#else
#  define STRINGMANIPULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // STRINGMANIPULATION_GLOBAL_H
