#pragma once

#include <QtGlobal>

#if defined(STRINGMANIPULATION_LIBRARY)
#  define STRINGMANIPULATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRINGMANIPULATIONSHARED_EXPORT Q_DECL_IMPORT
#endif
